export type OccupationLocale = "es" | "en";
export type OccupationOption = { id: string; es: string; en: string };

export const OCCUPATIONS: OccupationOption[] = [
  { id: "doctor", es: "Doctor / Doctora", en: "Doctor" },
  { id: "nurse", es: "Enfermero / Enfermera", en: "Nurse" },
  { id: "teacher", es: "Profesor / Profesora", en: "Teacher" },
  { id: "engineer", es: "Ingeniero / Ingeniera", en: "Engineer" },
  { id: "lawyer", es: "Abogado / Abogada", en: "Lawyer" },
  { id: "business-owner", es: "Empresario / Empresaria", en: "Business Owner" },
  { id: "student", es: "Estudiante", en: "Student" },
  { id: "software-developer", es: "Desarrollador / Desarrolladora de software", en: "Software Developer" },
  { id: "architect", es: "Arquitecto / Arquitecta", en: "Architect" },
  { id: "chef", es: "Chef", en: "Chef" },
  { id: "photographer", es: "Fotógrafo / Fotógrafa", en: "Photographer" },
  { id: "model", es: "Modelo", en: "Model" },
  { id: "accountant", es: "Contador / Contadora", en: "Accountant" },
  { id: "administrator", es: "Administrador / Administradora", en: "Administrator" },
  { id: "salesperson", es: "Vendedor / Vendedora", en: "Salesperson" },
  { id: "marketing-specialist", es: "Especialista en marketing", en: "Marketing Specialist" },
  { id: "graphic-designer", es: "Diseñador / Diseñadora gráfico", en: "Graphic Designer" },
  { id: "web-designer", es: "Diseñador / Diseñadora web", en: "Web Designer" },
  { id: "data-analyst", es: "Analista de datos", en: "Data Analyst" },
  { id: "data-scientist", es: "Científico / Científica de datos", en: "Data Scientist" },
  { id: "product-manager", es: "Gerente de producto", en: "Product Manager" },
  { id: "project-manager", es: "Gerente de proyectos", en: "Project Manager" },
  { id: "human-resources", es: "Profesional de recursos humanos", en: "Human Resources Professional" },
  { id: "recruiter", es: "Reclutador / Reclutadora", en: "Recruiter" },
  { id: "psychologist", es: "Psicólogo / Psicóloga", en: "Psychologist" },
  { id: "therapist", es: "Terapeuta", en: "Therapist" },
  { id: "dentist", es: "Dentista", en: "Dentist" },
  { id: "pharmacist", es: "Farmacéutico / Farmacéutica", en: "Pharmacist" },
  { id: "veterinarian", es: "Veterinario / Veterinaria", en: "Veterinarian" },
  { id: "surgeon", es: "Cirujano / Cirujana", en: "Surgeon" },
  { id: "paramedic", es: "Paramédico / Paramédica", en: "Paramedic" },
  { id: "physical-therapist", es: "Fisioterapeuta", en: "Physical Therapist" },
  { id: "nutritionist", es: "Nutriólogo / Nutrióloga", en: "Nutritionist" },
  { id: "scientist", es: "Científico / Científica", en: "Scientist" },
  { id: "researcher", es: "Investigador / Investigadora", en: "Researcher" },
  { id: "biologist", es: "Biólogo / Bióloga", en: "Biologist" },
  { id: "chemist", es: "Químico / Química", en: "Chemist" },
  { id: "physicist", es: "Físico / Física", en: "Physicist" },
  { id: "civil-engineer", es: "Ingeniero / Ingeniera civil", en: "Civil Engineer" },
  { id: "mechanical-engineer", es: "Ingeniero / Ingeniera mecánico", en: "Mechanical Engineer" },
  { id: "electrical-engineer", es: "Ingeniero / Ingeniera eléctrico", en: "Electrical Engineer" },
  { id: "industrial-engineer", es: "Ingeniero / Ingeniera industrial", en: "Industrial Engineer" },
  { id: "aerospace-engineer", es: "Ingeniero / Ingeniera aeroespacial", en: "Aerospace Engineer" },
  { id: "ai-engineer", es: "Ingeniero / Ingeniera de IA", en: "AI Engineer" },
  { id: "cybersecurity-specialist", es: "Especialista en ciberseguridad", en: "Cybersecurity Specialist" },
  { id: "network-engineer", es: "Ingeniero / Ingeniera de redes", en: "Network Engineer" },
  { id: "it-support", es: "Especialista de soporte TI", en: "IT Support Specialist" },
  { id: "database-administrator", es: "Administrador / Administradora de bases de datos", en: "Database Administrator" },
  { id: "ux-designer", es: "Diseñador / Diseñadora UX", en: "UX Designer" },
  { id: "ui-designer", es: "Diseñador / Diseñadora UI", en: "UI Designer" },
  { id: "illustrator", es: "Ilustrador / Ilustradora", en: "Illustrator" },
  { id: "animator", es: "Animador / Animadora", en: "Animator" },
  { id: "video-editor", es: "Editor / Editora de video", en: "Video Editor" },
  { id: "filmmaker", es: "Cineasta", en: "Filmmaker" },
  { id: "director", es: "Director / Directora", en: "Director" },
  { id: "producer", es: "Productor / Productora", en: "Producer" },
  { id: "actor", es: "Actor / Actriz", en: "Actor" },
  { id: "musician", es: "Músico / Música", en: "Musician" },
  { id: "singer", es: "Cantante", en: "Singer" },
  { id: "dancer", es: "Bailarín / Bailarina", en: "Dancer" },
  { id: "writer", es: "Escritor / Escritora", en: "Writer" },
  { id: "journalist", es: "Periodista", en: "Journalist" },
  { id: "content-creator", es: "Creador / Creadora de contenido", en: "Content Creator" },
  { id: "influencer", es: "Influencer", en: "Influencer" },
  { id: "social-media-manager", es: "Social Media Manager", en: "Social Media Manager" },
  { id: "public-relations", es: "Especialista en relaciones públicas", en: "Public Relations Specialist" },
  { id: "copywriter", es: "Redactor / Redactora publicitario", en: "Copywriter" },
  { id: "translator", es: "Traductor / Traductora", en: "Translator" },
  { id: "interpreter", es: "Intérprete", en: "Interpreter" },
  { id: "librarian", es: "Bibliotecario / Bibliotecaria", en: "Librarian" },
  { id: "professor", es: "Catedrático / Catedrática", en: "Professor" },
  { id: "school-principal", es: "Director / Directora escolar", en: "School Principal" },
  { id: "coach", es: "Entrenador / Entrenadora", en: "Coach" },
  { id: "personal-trainer", es: "Entrenador / Entrenadora personal", en: "Personal Trainer" },
  { id: "athlete", es: "Atleta", en: "Athlete" },
  { id: "yoga-instructor", es: "Instructor / Instructora de yoga", en: "Yoga Instructor" },
  { id: "fitness-instructor", es: "Instructor / Instructora fitness", en: "Fitness Instructor" },
  { id: "police-officer", es: "Policía", en: "Police Officer" },
  { id: "firefighter", es: "Bombero / Bombera", en: "Firefighter" },
  { id: "military-officer", es: "Militar", en: "Military Officer" },
  { id: "security-guard", es: "Guardia de seguridad", en: "Security Guard" },
  { id: "detective", es: "Detective", en: "Detective" },
  { id: "judge", es: "Juez / Jueza", en: "Judge" },
  { id: "paralegal", es: "Asistente jurídico / Jurídica", en: "Paralegal" },
  { id: "real-estate-agent", es: "Agente inmobiliario", en: "Real Estate Agent" },
  { id: "insurance-agent", es: "Agente de seguros", en: "Insurance Agent" },
  { id: "banker", es: "Banquero / Banquera", en: "Banker" },
  { id: "financial-advisor", es: "Asesor / Asesora financiero", en: "Financial Advisor" },
  { id: "economist", es: "Economista", en: "Economist" },
  { id: "investment-analyst", es: "Analista de inversiones", en: "Investment Analyst" },
  { id: "entrepreneur", es: "Emprendedor / Emprendedora", en: "Entrepreneur" },
  { id: "consultant", es: "Consultor / Consultora", en: "Consultant" },
  { id: "operations-manager", es: "Gerente de operaciones", en: "Operations Manager" },
  { id: "store-manager", es: "Gerente de tienda", en: "Store Manager" },
  { id: "customer-service", es: "Representante de servicio al cliente", en: "Customer Service Representative" },
  { id: "receptionist", es: "Recepcionista", en: "Receptionist" },
  { id: "executive-assistant", es: "Asistente ejecutivo / Ejecutiva", en: "Executive Assistant" },
  { id: "secretary", es: "Secretario / Secretaria", en: "Secretary" },
  { id: "office-worker", es: "Oficinista", en: "Office Worker" },
  { id: "barista", es: "Barista", en: "Barista" },
  { id: "bartender", es: "Bartender", en: "Bartender" },
  { id: "waiter", es: "Mesero / Mesera", en: "Waiter / Waitress" },
  { id: "baker", es: "Panadero / Panadera", en: "Baker" },
  { id: "pastry-chef", es: "Repostero / Repostera", en: "Pastry Chef" },
  { id: "butcher", es: "Carnicero / Carnicera", en: "Butcher" },
  { id: "farmer", es: "Agricultor / Agricultora", en: "Farmer" },
  { id: "gardener", es: "Jardinero / Jardinera", en: "Gardener" },
  { id: "florist", es: "Florista", en: "Florist" },
  { id: "fashion-designer", es: "Diseñador / Diseñadora de moda", en: "Fashion Designer" },
  { id: "stylist", es: "Estilista", en: "Stylist" },
  { id: "hair-stylist", es: "Estilista de cabello", en: "Hair Stylist" },
  { id: "makeup-artist", es: "Maquillista", en: "Makeup Artist" },
  { id: "nail-technician", es: "Técnico / Técnica de uñas", en: "Nail Technician" },
  { id: "esthetician", es: "Esteticista", en: "Esthetician" },
  { id: "tailor", es: "Sastre / Modista", en: "Tailor" },
  { id: "jeweler", es: "Joyero / Joyera", en: "Jeweler" },
  { id: "interior-designer", es: "Diseñador / Diseñadora de interiores", en: "Interior Designer" },
  { id: "construction-worker", es: "Trabajador / Trabajadora de construcción", en: "Construction Worker" },
  { id: "carpenter", es: "Carpintero / Carpintera", en: "Carpenter" },
  { id: "electrician", es: "Electricista", en: "Electrician" },
  { id: "plumber", es: "Plomero / Plomera", en: "Plumber" },
  { id: "welder", es: "Soldador / Soldadora", en: "Welder" },
  { id: "mechanic", es: "Mecánico / Mecánica", en: "Mechanic" },
  { id: "truck-driver", es: "Conductor / Conductora de camión", en: "Truck Driver" },
  { id: "delivery-driver", es: "Repartidor / Repartidora", en: "Delivery Driver" },
  { id: "taxi-driver", es: "Taxista", en: "Taxi Driver" },
  { id: "pilot", es: "Piloto", en: "Pilot" },
  { id: "flight-attendant", es: "Sobrecargo / Auxiliar de vuelo", en: "Flight Attendant" },
  { id: "travel-agent", es: "Agente de viajes", en: "Travel Agent" },
  { id: "tour-guide", es: "Guía turístico / Turística", en: "Tour Guide" },
  { id: "hotel-manager", es: "Gerente de hotel", en: "Hotel Manager" },
  { id: "housekeeper", es: "Personal de limpieza", en: "Housekeeper" },
  { id: "caregiver", es: "Cuidador / Cuidadora", en: "Caregiver" },
  { id: "social-worker", es: "Trabajador / Trabajadora social", en: "Social Worker" },
  { id: "childcare-worker", es: "Cuidador / Cuidadora infantil", en: "Childcare Worker" },
  { id: "stay-at-home-parent", es: "Padre / Madre dedicado al hogar", en: "Stay-at-Home Parent" },
  { id: "retired", es: "Jubilado / Jubilada", en: "Retired" },
  { id: "freelancer", es: "Freelancer", en: "Freelancer" },
  { id: "remote-worker", es: "Trabajador / Trabajadora remoto", en: "Remote Worker" },
  { id: "unemployed", es: "Sin empleo", en: "Unemployed" },
];

export function getOccupationLabel(id: string | undefined, locale: OccupationLocale = "es") {
  if (!id) return "";
  const option = OCCUPATIONS.find((item) => item.id === id);
  return option ? option[locale] : "";
}

export function getOccupationPromptValue(id: string | undefined, customValue?: string) {
  if (!id) return "";
  if (id === "custom") return customValue?.trim() || "";
  return OCCUPATIONS.find((item) => item.id === id)?.en || "";
}