"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {listLegalPolicies,acceptLegalPolicies} from "@/lib/legal-api";
import type {LegalPolicy,LegalAcceptanceBundle} from "@/types/legal";
export function LegalConsentModal({open,onClose,onAccepted,persist=true}:{open:boolean;onClose:()=>void;onAccepted:(bundle:LegalAcceptanceBundle)=>void;persist?:boolean}){
 const [policies,setPolicies]=useState<LegalPolicy[]>([]),[accepted,setAccepted]=useState<number[]>([]);const [immediate,setImmediate]=useState(false),[first,setFirst]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(open)void listLegalPolicies().then(setPolicies).catch(()=>setError("No fue posible cargar las políticas."))},[open]);
 const required=useMemo(()=>policies.filter(p=>p.is_required),[policies]); const ready=required.length>0&&required.every(p=>accepted.includes(p.id))&&immediate&&first;
 if(!open)return null; const bundle=():LegalAcceptanceBundle=>({acceptances:required.map(p=>({document_id:p.id,version:p.version})),immediate_service_start:immediate,first_token_activation_acknowledged:first});
 async function confirm(){if(!ready)return;setBusy(true);setError("");try{const b=bundle();if(persist)await acceptLegalPolicies(b);onAccepted(b)}catch(e){setError(e instanceof Error?e.message:"No fue posible guardar la aceptación.")}finally{setBusy(false)}}
 return <div className="legalModalBackdrop" role="dialog" aria-modal="true"><div className="legalModalCard"><button className="legalModalClose" onClick={onClose} aria-label="Cerrar">×</button><span className="eyebrow">ANTES DE CONTINUAR</span><h2>Revisa y acepta las políticas</h2><p>Solo debes hacerlo cuando exista una versión nueva o aún no la hayas aceptado.</p><div className="legalModalList">{required.map(p=><label key={p.id}><input type="checkbox" checked={accepted.includes(p.id)} onChange={e=>setAccepted(x=>e.target.checked?[...x,p.id]:x.filter(id=>id!==p.id))}/><span><b>{p.title}</b><small>Versión {p.version} · <Link target="_blank" href={`/legal/${p.document_type}`}>Abrir política</Link></small></span></label>)}</div><label className="legalModalCheck"><input type="checkbox" checked={immediate} onChange={e=>setImmediate(e.target.checked)}/><span>Solicito que el servicio digital comience inmediatamente.</span></label><label className="legalModalCheck"><input type="checkbox" checked={first} onChange={e=>setFirst(e.target.checked)}/><span>Entiendo que el primer consumo activa la bolsa y puede afectar el reembolso.</span></label>{error&&<p className="legalModalError">{error}</p>}<button className="exactSubmit" disabled={!ready||busy} onClick={()=>void confirm()}>{busy?"Guardando…":"Aceptar y continuar"}</button></div></div>
}
