export type OccupationLocale = "es" | "en";
export type OccupationOption = { id: string; es: string; en: string };

export const OCCUPATIONS: OccupationOption[] = [
  { id: "doctor", es: "Doctora", en: "Doctor" },
  { id: "nurse", es: "Enfermera", en: "Nurse" },
  { id: "teacher", es: "Profesora", en: "Teacher" },
  { id: "engineer", es: "Ingeniera", en: "Engineer" },
  { id: "lawyer", es: "Abogada", en: "Lawyer" },
  { id: "business-owner", es: "Empresaria", en: "Business Owner" },
  { id: "student", es: "Estudiante", en: "Student" },
  { id: "software-developer", es: "Desarrolladora de software", en: "Software Developer" },
  { id: "architect", es: "Arquitecta", en: "Architect" },
  { id: "chef", es: "Chef", en: "Chef" },
  { id: "photographer", es: "Fotógrafa", en: "Photographer" },
  { id: "model", es: "Modelo", en: "Model" },
  { id: "accountant", es: "Contadora", en: "Accountant" },
  { id: "administrator", es: "Administradora", en: "Administrator" },
  { id: "salesperson", es: "Vendedora", en: "Salesperson" },
  { id: "marketing-specialist", es: "Especialista en marketing", en: "Marketing Specialist" },
  { id: "graphic-designer", es: "Diseñadora gráfica", en: "Graphic Designer" },
  { id: "web-designer", es: "Diseñadora web", en: "Web Designer" },
  { id: "data-analyst", es: "Analista de datos", en: "Data Analyst" },
  { id: "data-scientist", es: "Científica de datos", en: "Data Scientist" },
  { id: "product-manager", es: "Gerente de producto", en: "Product Manager" },
  { id: "project-manager", es: "Gerente de proyectos", en: "Project Manager" },
  { id: "human-resources", es: "Profesional de recursos humanos", en: "Human Resources Professional" },
  { id: "recruiter", es: "Reclutadora", en: "Recruiter" },
  { id: "psychologist", es: "Psicóloga", en: "Psychologist" },
  { id: "therapist", es: "Terapeuta", en: "Therapist" },
  { id: "dentist", es: "Dentista", en: "Dentist" },
  { id: "pharmacist", es: "Farmacéutica", en: "Pharmacist" },
  { id: "veterinarian", es: "Veterinaria", en: "Veterinarian" },
  { id: "surgeon", es: "Cirujana", en: "Surgeon" },
  { id: "paramedic", es: "Paramédica", en: "Paramedic" },
  { id: "physical-therapist", es: "Fisioterapeuta", en: "Physical Therapist" },
  { id: "nutritionist", es: "Nutrióloga", en: "Nutritionist" },
  { id: "scientist", es: "Científica", en: "Scientist" },
  { id: "researcher", es: "Investigadora", en: "Researcher" },
  { id: "biologist", es: "Bióloga", en: "Biologist" },
  { id: "chemist", es: "Química", en: "Chemist" },
  { id: "physicist", es: "Física", en: "Physicist" },
  { id: "civil-engineer", es: "Ingeniera civil", en: "Civil Engineer" },
  { id: "mechanical-engineer", es: "Ingeniera mecánica", en: "Mechanical Engineer" },
  { id: "electrical-engineer", es: "Ingeniera eléctrica", en: "Electrical Engineer" },
  { id: "industrial-engineer", es: "Ingeniera industrial", en: "Industrial Engineer" },
  { id: "aerospace-engineer", es: "Ingeniera aeroespacial", en: "Aerospace Engineer" },
  { id: "ai-engineer", es: "Ingeniera de IA", en: "AI Engineer" },
  { id: "cybersecurity-specialist", es: "Especialista en ciberseguridad", en: "Cybersecurity Specialist" },
  { id: "network-engineer", es: "Ingeniera de redes", en: "Network Engineer" },
  { id: "it-support", es: "Especialista de soporte TI", en: "IT Support Specialist" },
  { id: "database-administrator", es: "Administradora de bases de datos", en: "Database Administrator" },
  { id: "ux-designer", es: "Diseñadora UX", en: "UX Designer" },
  { id: "ui-designer", es: "Diseñadora UI", en: "UI Designer" },
  { id: "illustrator", es: "Ilustradora", en: "Illustrator" },
  { id: "animator", es: "Animadora", en: "Animator" },
  { id: "video-editor", es: "Editora de video", en: "Video Editor" },
  { id: "filmmaker", es: "Cineasta", en: "Filmmaker" },
  { id: "director", es: "Directora", en: "Director" },
  { id: "producer", es: "Productora", en: "Producer" },
  { id: "actor", es: "Actriz", en: "Actor" },
  { id: "musician", es: "Música", en: "Musician" },
  { id: "singer", es: "Cantante", en: "Singer" },
  { id: "dancer", es: "Bailarina", en: "Dancer" },
  { id: "writer", es: "Escritora", en: "Writer" },
  { id: "journalist", es: "Periodista", en: "Journalist" },
  { id: "content-creator", es: "Creadora de contenido", en: "Content Creator" },
  { id: "influencer", es: "Influencer", en: "Influencer" },
  { id: "social-media-manager", es: "Social Media Manager", en: "Social Media Manager" },
  { id: "public-relations", es: "Especialista en relaciones públicas", en: "Public Relations Specialist" },
  { id: "copywriter", es: "Redactora publicitaria", en: "Copywriter" },
  { id: "translator", es: "Traductora", en: "Translator" },
  { id: "interpreter", es: "Intérprete", en: "Interpreter" },
  { id: "librarian", es: "Bibliotecaria", en: "Librarian" },
  { id: "professor", es: "Catedrática", en: "Professor" },
  { id: "school-principal", es: "Directora escolar", en: "School Principal" },
  { id: "coach", es: "Entrenadora", en: "Coach" },
  { id: "personal-trainer", es: "Entrenadora personal", en: "Personal Trainer" },
  { id: "athlete", es: "Atleta", en: "Athlete" },
  { id: "yoga-instructor", es: "Instructora de yoga", en: "Yoga Instructor" },
  { id: "fitness-instructor", es: "Instructora fitness", en: "Fitness Instructor" },
  { id: "police-officer", es: "Policía", en: "Police Officer" },
  { id: "firefighter", es: "Bombera", en: "Firefighter" },
  { id: "military-officer", es: "Militar", en: "Military Officer" },
  { id: "security-guard", es: "Guardia de seguridad", en: "Security Guard" },
  { id: "detective", es: "Detective", en: "Detective" },
  { id: "judge", es: "Jueza", en: "Judge" },
  { id: "paralegal", es: "Jurídica", en: "Paralegal" },
  { id: "real-estate-agent", es: "Agente inmobiliario", en: "Real Estate Agent" },
  { id: "insurance-agent", es: "Agente de seguros", en: "Insurance Agent" },
  { id: "banker", es: "Banquera", en: "Banker" },
  { id: "financial-advisor", es: "Asesora financiera", en: "Financial Advisor" },
  { id: "economist", es: "Economista", en: "Economist" },
  { id: "investment-analyst", es: "Analista de inversiones", en: "Investment Analyst" },
  { id: "entrepreneur", es: "Emprendedora", en: "Entrepreneur" },
  { id: "consultant", es: "Consultora", en: "Consultant" },
  { id: "operations-manager", es: "Gerente de operaciones", en: "Operations Manager" },
  { id: "store-manager", es: "Gerente de tienda", en: "Store Manager" },
  { id: "customer-service", es: "Representante de servicio al cliente", en: "Customer Service Representative" },
  { id: "receptionist", es: "Recepcionista", en: "Receptionist" },
  { id: "executive-assistant", es: "Asistente ejecutiva", en: "Executive Assistant" },
  { id: "secretary", es: "Secretaria", en: "Secretary" },
  { id: "office-worker", es: "Oficinista", en: "Office Worker" },
  { id: "barista", es: "Barista", en: "Barista" },
  { id: "bartender", es: "Bartender", en: "Bartender" },
  { id: "waiter", es: "Mesera", en: "Waiter / Waitress" },
  { id: "baker", es: "Panadera", en: "Baker" },
  { id: "pastry-chef", es: "Repostera", en: "Pastry Chef" },
  { id: "butcher", es: "Carnicera", en: "Butcher" },
  { id: "farmer", es: "Agricultora", en: "Farmer" },
  { id: "gardener", es: "Jardinera", en: "Gardener" },
  { id: "florist", es: "Florista", en: "Florist" },
  { id: "fashion-designer", es: "Diseñadora de moda", en: "Fashion Designer" },
  { id: "stylist", es: "Estilista", en: "Stylist" },
  { id: "hair-stylist", es: "Estilista de cabello", en: "Hair Stylist" },
  { id: "makeup-artist", es: "Maquillista", en: "Makeup Artist" },
  { id: "nail-technician", es: "Técnica de uñas", en: "Nail Technician" },
  { id: "esthetician", es: "Esteticista", en: "Esthetician" },
  { id: "tailor", es: "Modista", en: "Tailor" },
  { id: "jeweler", es: "Joyera", en: "Jeweler" },
  { id: "interior-designer", es: "Diseñadora de interiores", en: "Interior Designer" },
  { id: "construction-worker", es: "Trabajadora de construcción", en: "Construction Worker" },
  { id: "carpenter", es: "Carpintera", en: "Carpenter" },
  { id: "electrician", es: "Electricista", en: "Electrician" },
  { id: "plumber", es: "Plomera", en: "Plumber" },
  { id: "welder", es: "Soldadora", en: "Welder" },
  { id: "mechanic", es: "Mecánica automotriz", en: "Mechanic" },
  { id: "truck-driver", es: "Conductora de camión", en: "Truck Driver" },
  { id: "delivery-driver", es: "Repartidora", en: "Delivery Driver" },
  { id: "taxi-driver", es: "Taxista", en: "Taxi Driver" },
  { id: "pilot", es: "Piloto", en: "Pilot" },
  { id: "flight-attendant", es: "Auxiliar de vuelo", en: "Flight Attendant" },
  { id: "travel-agent", es: "Agente de viajes", en: "Travel Agent" },
  { id: "tour-guide", es: "Guía turística", en: "Tour Guide" },
  { id: "hotel-manager", es: "Gerente de hotel", en: "Hotel Manager" },
  { id: "housekeeper", es: "Personal de limpieza", en: "Housekeeper" },
  { id: "caregiver", es: "Cuidadora", en: "Caregiver" },
  { id: "social-worker", es: "Trabajadora social", en: "Social Worker" },
  { id: "childcare-worker", es: "Cuidadora infantil", en: "Childcare Worker" },
  { id: "stay-at-home-parent", es: "Madre dedicada al hogar", en: "Stay-at-Home Parent" },
  { id: "retired", es: "Jubilada", en: "Retired" },
  { id: "freelancer", es: "Freelancer", en: "Freelancer" },
  { id: "remote-worker", es: "Trabajadora remota", en: "Remote Worker" },
  { id: "unemployed", es: "Sin empleo", en: "Unemployed" },
];

export function getOccupationLabel(id: string | undefined, locale: OccupationLocale = "es") {
  if (!id) return "";
  const option = OCCUPATIONS.find((item) => item.id === id);
  return option ? option[locale] : "";
}

export function getOccupationPromptValue(id: string | undefined, customValue?: string) {
  if (!id) return "";
  if (id === "custom") return customValue?.trim() || "";
  return OCCUPATIONS.find((item) => item.id === id)?.en || "";
}

export type OccupationGenerationContext = {
  place: string;
  clothes: string;
};

// Keep outfit prompting local and deterministic. Each catalog occupation gets a
// concrete SFW wardrobe direction instead of a vague "professional outfit".
const OCCUPATION_CLOTHES: Record<string, string> = {
  doctor: "wear a tailored white medical coat over a fitted ivory blouse, slim ankle-length trousers, clean leather pumps, subtle professional accessories, polished realistic doctor outfit, tasteful and SFW",
  nurse: "wear a clean fitted modern nurse scrubs with a flattering V-neck scrub top, matching tapered scrub pants, white clinical sneakers, discreet nurse badge and practical watch, polished realistic healthcare outfit, tasteful and SFW",
  teacher: "wear a fitted soft knit top tucked into a high-waisted pleated midi skirt, cropped tailored blazer, elegant loafers, refined classroom-ready teacher outfit, feminine, polished and SFW",
  engineer: "wear a fitted button-up blouse, high-waisted tailored trousers, structured lightweight blazer, sleek ankle boots, modern polished engineering-professional outfit, practical, feminine and SFW",
  lawyer: "wear a fitted ivory blouse, high-waisted pencil skirt, sharply tailored blazer, elegant closed-toe heels, sophisticated realistic lawyer outfit, polished and SFW",
  "business-owner": "wear a luxury fitted blouse, high-waisted tailored wide-leg trousers, cropped structured blazer, elegant heels, confident upscale entrepreneur outfit, polished and SFW",
  student: "wear a cute red plaid pleated mini skirt, fitted white crop top, cropped cardigan, red high heels, fashionable campus outfit, tasteful and SFW",
  "software-developer": "wear a fitted premium ribbed top, high-waisted dark jeans, cropped smart blazer, clean minimalist sneakers, modern stylish software-developer outfit, polished, comfortable and SFW",
  architect: "wear a fitted black mock-neck top, high-waisted tailored trousers, architectural-cut blazer, sleek ankle boots, minimalist designer architect outfit, polished and SFW",
  chef: "wear a crisp fitted double-breasted chef jacket, tailored black chef trousers, waist apron, professional non-slip shoes, refined realistic chef uniform, clean and SFW",
  photographer: "wear a fitted black top, high-waisted utility trousers, cropped leather or canvas jacket, ankle boots, discreet camera-utility belt, fashionable professional photographer outfit, realistic and SFW",
  model: "wear a fashion-forward fitted designer top, high-waisted mini skirt, elegant heels, tasteful editorial accessories, glamorous contemporary model off-duty outfit, polished and SFW",
  accountant: "wear a fitted satin blouse, high-waisted tailored trousers, slim blazer, classic pumps, elegant realistic accountant office outfit, polished and SFW",
  administrator: "wear a fitted blouse, high-waisted pencil skirt, tailored blazer, elegant low heels, refined administrative professional outfit, polished and SFW",
  salesperson: "wear a fitted fashionable blouse, sleek high-waisted trousers, cropped blazer, elegant heels, upscale retail sales outfit, approachable, polished and SFW",
  "marketing-specialist": "wear a fashionable fitted blouse, high-waisted tailored trousers, statement cropped blazer, stylish heels, creative corporate marketing outfit, polished and SFW",
  "graphic-designer": "wear a fitted modern top, high-waisted wide-leg trousers, cropped creative jacket, stylish sneakers, tasteful statement accessories, contemporary graphic-designer outfit, polished and SFW",
  "web-designer": "wear a fitted minimalist top, high-waisted tailored jeans, lightweight cropped blazer, clean sneakers, modern digital-creative outfit, stylish and SFW",
  "data-analyst": "wear a fitted knit blouse, high-waisted tailored trousers, clean structured blazer, elegant loafers, smart modern data-analyst outfit, polished and SFW",
  "data-scientist": "wear a fitted smart-casual blouse, tailored high-waisted trousers, modern blazer, minimalist sneakers, refined technology-professional outfit, polished and SFW",
  "product-manager": "wear a premium fitted top, high-waisted tailored trousers, sharp cropped blazer, elegant pumps, confident modern product-manager outfit, polished and SFW",
  "project-manager": "wear a fitted blouse, tailored high-waisted trousers, structured blazer, elegant low heels, organized executive project-manager outfit, polished and SFW",
  "human-resources": "wear a soft fitted blouse, high-waisted midi skirt, refined blazer, elegant pumps, approachable human-resources professional outfit, polished and SFW",
  recruiter: "wear a fitted elegant blouse, tailored ankle trousers, cropped blazer, chic low heels, polished recruiter outfit, approachable and SFW",
  psychologist: "wear a soft fitted knit blouse, elegant midi skirt, light tailored cardigan, refined low heels, warm professional psychologist outfit, polished and SFW",
  therapist: "wear a soft fitted blouse, high-waisted flowing midi skirt, elegant cardigan, tasteful flats, calm approachable therapist outfit, polished and SFW",
  dentist: "wear a clean fitted dental scrub top, matching tapered scrub pants, short white clinical coat, white professional shoes, polished realistic dentist outfit, practical and SFW",
  pharmacist: "wear a fitted blouse and tailored trousers under a clean white pharmacist coat, comfortable polished shoes, discreet professional badge, realistic pharmacy outfit, SFW",
  veterinarian: "wear a fitted veterinary scrub top, tapered scrub pants, lightweight white clinic coat, clean practical sneakers, polished realistic veterinarian outfit, SFW",
  surgeon: "wear a clean fitted surgical scrubs, tapered scrub trousers, surgical cap carried or neatly worn as appropriate, clinical shoes, authentic polished surgeon outfit, realistic and SFW",
  paramedic: "wear a fitted paramedic polo or uniform shirt, tailored tactical medical trousers with reflective details, utility belt, sturdy boots, authentic emergency-medical outfit, practical and SFW",
  "physical-therapist": "wear a fitted athletic polo, tailored stretch trousers, clean supportive sneakers, minimal clinic accessories, polished physical-therapist outfit, professional and SFW",
  nutritionist: "wear a fitted elegant blouse, high-waisted tailored trousers, light clinical coat, refined low heels, clean modern nutritionist outfit, polished and SFW",
  scientist: "wear a fitted professional blouse and tailored trousers under a clean laboratory coat, closed-toe lab shoes, subtle safety glasses, realistic scientist outfit, polished and SFW",
  researcher: "wear a fitted smart blouse, tailored trousers, clean research lab coat, closed-toe shoes, understated professional accessories, realistic researcher outfit, polished and SFW",
  biologist: "wear a fitted practical blouse, tailored lab trousers, clean laboratory coat, closed-toe shoes, subtle lab accessories, realistic biologist outfit, polished and SFW",
  chemist: "wear a fitted professional top and tailored trousers under a clean lab coat, safety glasses, closed-toe laboratory shoes, realistic chemist outfit, polished and SFW",
  physicist: "wear a fitted smart-casual blouse, high-waisted tailored trousers, minimalist blazer or lab coat, elegant loafers, refined physicist outfit, polished and SFW",
  "civil-engineer": "wear a fitted collared shirt, tailored utility trousers, high-visibility vest used neatly, hard hat, sturdy work boots, polished realistic civil-engineer outfit, practical and SFW",
  "mechanical-engineer": "wear a fitted work shirt, tailored utility trousers, clean lightweight work jacket, protective boots, practical engineering accessories, polished mechanical-engineer outfit, SFW",
  "electrical-engineer": "wear a fitted professional work shirt, tailored utility trousers, clean safety vest, protective work boots, realistic electrical-engineer outfit, polished and SFW",
  "industrial-engineer": "wear a fitted blouse, tailored high-waisted trousers, structured blazer with optional safety vest, polished work shoes, modern industrial-engineer outfit, SFW",
  "aerospace-engineer": "wear a fitted technical blouse, tailored trousers, sleek structured jacket, clean work shoes, modern aerospace-engineer outfit, polished and SFW",
  "ai-engineer": "wear a fitted premium tech top, high-waisted tailored trousers, minimalist cropped blazer, sleek sneakers, futuristic but realistic AI-engineer outfit, polished and SFW",
  "cybersecurity-specialist": "wear a fitted dark mock-neck top, tailored black trousers, structured minimalist blazer, sleek boots, sophisticated cybersecurity-professional outfit, polished and SFW",
  "network-engineer": "wear a fitted technical polo, tailored utility trousers, lightweight smart jacket, clean practical shoes, realistic network-engineer outfit, polished and SFW",
  "it-support": "wear a fitted company polo, tailored dark trousers, lightweight utility jacket, clean sneakers, realistic IT-support outfit, practical, polished and SFW",
  "database-administrator": "wear a fitted minimalist blouse, high-waisted tailored trousers, clean blazer, stylish loafers, smart database-administrator outfit, polished and SFW",
  "ux-designer": "wear a fitted contemporary top, high-waisted wide-leg trousers, cropped designer jacket, fashionable sneakers, tasteful creative accessories, polished UX-designer outfit, SFW",
  "ui-designer": "wear a fitted modern top, high-waisted tailored trousers, cropped fashion blazer, sleek sneakers, refined creative-tech outfit, polished and SFW",
  illustrator: "wear a fitted artistic top, high-waisted relaxed trousers, cropped creative jacket, stylish ankle boots, subtle artsy accessories, polished illustrator outfit, SFW",
  animator: "wear a fitted graphic knit top, high-waisted casual trousers, cropped jacket, fashionable sneakers, contemporary animation-studio outfit, polished and SFW",
  "video-editor": "wear a fitted dark top, high-waisted jeans or tailored cargo trousers, cropped utility jacket, sleek sneakers, modern video-editor outfit, polished and SFW",
  filmmaker: "wear a fitted black top, high-waisted utility trousers, stylish field jacket, ankle boots, subtle production accessories, cinematic filmmaker outfit, realistic and SFW",
  director: "wear a fitted black blouse, high-waisted tailored trousers, statement structured jacket, sleek boots, confident film-director outfit, fashionable and SFW",
  producer: "wear a elegant fitted blouse, tailored high-waisted trousers, luxury blazer, sophisticated heels, polished film-producer outfit, refined and SFW",
  actor: "wear a fashionable fitted top, high-waisted skirt or tailored trousers, chic cropped jacket, elegant heels, camera-ready actor off-duty outfit, tasteful and SFW",
  musician: "wear a stylish fitted stage-inspired top, high-waisted leather-look trousers or skirt, cropped jacket, heeled ankle boots, fashionable musician outfit, glamorous but SFW",
  singer: "wear a elegant fitted performance-inspired top, high-waisted statement skirt, chic cropped jacket, refined heels, glamorous singer outfit, tasteful and SFW",
  dancer: "wear a fitted long-sleeve dance top, high-waisted performance leggings or dance skirt, light wrap layer, dance shoes, elegant dancer outfit, athletic and SFW",
  writer: "wear a fitted soft blouse, high-waisted trousers or midi skirt, cozy tailored cardigan, elegant loafers, refined writer outfit, stylish and SFW",
  journalist: "wear a fitted blouse, high-waisted tailored trousers, practical trench or cropped blazer, ankle boots, polished field-journalist outfit, realistic and SFW",
  "content-creator": "wear a trendy fitted cropped top with tasteful midriff, high-waisted fashion trousers or mini skirt, stylish jacket, statement heels, camera-ready creator outfit, glamorous and SFW",
  influencer: "wear a fashion-forward fitted crop top with tasteful midriff, high-waisted mini skirt, chic cropped jacket, elegant heels, polished influencer outfit, glamorous and SFW",
  "social-media-manager": "wear a trendy fitted blouse, high-waisted tailored jeans, cropped blazer, fashionable sneakers or heels, modern social-media professional outfit, polished and SFW",
  "public-relations": "wear a elegant fitted blouse, high-waisted pencil skirt, statement blazer, refined heels, sophisticated public-relations outfit, polished and SFW",
  copywriter: "wear a fitted creative blouse, high-waisted trousers, cropped casual blazer, stylish loafers, contemporary copywriter outfit, polished and SFW",
  translator: "wear a fitted elegant blouse, tailored trousers or midi skirt, light blazer, refined loafers, polished translator outfit, understated and SFW",
  interpreter: "wear a fitted formal blouse, high-waisted tailored trousers, structured blazer, elegant low heels, professional interpreter outfit, polished and SFW",
  librarian: "wear a fitted knit blouse, high-waisted pleated midi skirt, soft cardigan, elegant loafers, charming modern librarian outfit, polished and SFW",
  professor: "wear a fitted turtleneck or blouse, high-waisted tailored midi skirt, sophisticated blazer, elegant loafers or heels, refined university-professor outfit, polished and SFW",
  "school-principal": "wear a elegant fitted blouse, high-waisted pencil skirt, structured blazer, classic pumps, authoritative school-principal outfit, polished and SFW",
  coach: "wear a fitted performance polo, high-waisted athletic trousers, lightweight track jacket, clean trainers, polished coach outfit, sporty and SFW",
  "personal-trainer": "wear a fitted athletic top, high-waisted performance leggings, cropped zip jacket, premium training sneakers, stylish personal-trainer outfit, athletic and SFW",
  athlete: "wear a fitted performance top, high-waisted athletic leggings or shorts with appropriate coverage, lightweight sport jacket, professional trainers, realistic athlete outfit, SFW",
  "yoga-instructor": "wear a fitted longline yoga top, high-waisted yoga leggings, light wrap jacket, clean studio footwear or barefoot as appropriate, elegant yoga-instructor outfit, SFW",
  "fitness-instructor": "wear a fitted performance crop top with tasteful coverage, high-waisted training leggings, cropped athletic jacket, premium sneakers, energetic fitness-instructor outfit, SFW",
  "police-officer": "wear a authentic fitted police duty shirt, tailored uniform trousers, duty belt, polished practical boots, professional realistic police-officer uniform, non-tactical presentation and SFW",
  firefighter: "wear a fitted fire-station duty T-shirt or polo, tailored station trousers, utility belt, sturdy station boots, realistic firefighter station outfit, professional and SFW",
  "military-officer": "wear a formal fitted service uniform jacket, matching tailored trousers or regulation skirt, polished shoes, restrained insignia, professional military-officer dress uniform, realistic and SFW",
  "security-guard": "wear a fitted professional security shirt, tailored dark uniform trousers, utility belt, polished boots, realistic security-guard uniform, neat and SFW",
  detective: "wear a fitted blouse, high-waisted tailored trousers, practical long coat or blazer, ankle boots, subtle badge accessory, stylish realistic detective outfit, SFW",
  judge: "wear a elegant professional blouse and tailored skirt beneath a formal judicial robe, refined closed-toe shoes, realistic judge outfit, dignified and SFW",
  paralegal: "wear a fitted blouse, high-waisted pencil skirt or tailored trousers, structured blazer, elegant pumps, polished paralegal outfit, professional and SFW",
  "real-estate-agent": "wear a fitted luxury blouse, high-waisted pencil skirt, tailored blazer, elegant heels, upscale real-estate-agent outfit, confident, polished and SFW",
  "insurance-agent": "wear a fitted blouse, tailored high-waisted trousers, classic blazer, elegant pumps, trustworthy insurance-agent outfit, polished and SFW",
  banker: "wear a fitted silk blouse, high-waisted tailored trousers or pencil skirt, sharp blazer, classic heels, sophisticated banker outfit, polished and SFW",
  "financial-advisor": "wear a elegant fitted blouse, tailored trousers, structured blazer, refined pumps, premium financial-advisor outfit, polished and SFW",
  economist: "wear a fitted sophisticated blouse, high-waisted tailored trousers, minimalist blazer, elegant loafers, refined economist outfit, polished and SFW",
  "investment-analyst": "wear a fitted silk blouse, high-waisted tailored trousers, sharp blazer, elegant heels, sophisticated investment-analyst outfit, polished and SFW",
  entrepreneur: "wear a fashionable fitted blouse, high-waisted tailored trousers, statement blazer, elegant heels, confident entrepreneur outfit, upscale and SFW",
  consultant: "wear a fitted premium blouse, tailored high-waisted trousers, crisp blazer, elegant pumps, sophisticated consultant outfit, polished and SFW",
  "operations-manager": "wear a fitted blouse, tailored trousers, structured blazer, practical elegant shoes, confident operations-manager outfit, polished and SFW",
  "store-manager": "wear a fitted fashionable blouse, high-waisted tailored trousers, retail-ready blazer, elegant low heels, polished store-manager outfit, SFW",
  "customer-service": "wear a fitted company blouse or polo, tailored trousers, light blazer, comfortable polished shoes, approachable customer-service outfit, neat and SFW",
  receptionist: "wear a elegant fitted blouse, high-waisted pencil skirt, cropped blazer, refined low heels, polished receptionist outfit, welcoming and SFW",
  "executive-assistant": "wear a fitted silk blouse, high-waisted tailored skirt or trousers, refined blazer, elegant pumps, sophisticated executive-assistant outfit, polished and SFW",
  secretary: "wear a fitted professional blouse, high-waisted pencil skirt, tailored cardigan or blazer, classic pumps, polished secretary outfit, elegant and SFW",
  "office-worker": "wear a fitted smart blouse, high-waisted tailored trousers, cropped blazer, elegant loafers, modern office-worker outfit, polished and SFW",
  barista: "wear a fitted black or white T-shirt, high-waisted dark jeans, stylish waist apron, clean sneakers, modern artisan-barista outfit, neat, realistic and SFW",
  bartender: "wear a fitted black blouse, high-waisted tailored trousers, sleek waist apron, polished ankle boots, chic upscale-bartender outfit, realistic and SFW",
  waiter: "wear a fitted white service blouse, high-waisted black trousers or knee-length skirt, tailored waist apron, polished service shoes, upscale restaurant-server outfit, SFW",
  baker: "wear a fitted chef jacket or blouse, tailored work trousers, neat apron, practical non-slip shoes, charming professional baker outfit, clean and SFW",
  "pastry-chef": "wear a crisp fitted pastry-chef jacket, tailored trousers, elegant waist apron, professional kitchen shoes, refined pastry-chef uniform, clean and SFW",
  butcher: "wear a fitted work shirt, practical tailored trousers, clean protective apron, sturdy non-slip shoes, authentic butcher-shop outfit, realistic and SFW",
  farmer: "wear a fitted plaid or cotton shirt, high-waisted work jeans, practical utility vest, sturdy boots, stylish realistic farmer outfit, functional and SFW",
  gardener: "wear a fitted breathable top, high-waisted utility trousers, light work overshirt, gardening boots, practical gloves, stylish gardener outfit, realistic and SFW",
  florist: "wear a fitted soft blouse, high-waisted trousers or midi skirt, elegant work apron, comfortable stylish shoes, romantic modern florist outfit, polished and SFW",
  "fashion-designer": "wear a fashion-forward fitted top, high-waisted statement trousers or skirt, sculpted designer jacket, elegant heels, creative fashion-designer outfit, polished and SFW",
  stylist: "wear a trendy fitted top, high-waisted fashion trousers, statement cropped jacket, elegant heels, fashion-stylist outfit, chic, polished and SFW",
  "hair-stylist": "wear a fitted fashionable black top, high-waisted sleek trousers, stylish salon apron, chic ankle boots, modern hair-stylist outfit, polished and SFW",
  "makeup-artist": "wear a fitted chic black top, high-waisted tailored trousers, stylish utility apron or belt, elegant ankle boots, polished makeup-artist outfit, fashionable and SFW",
  "nail-technician": "wear a fitted stylish blouse, high-waisted tailored trousers, neat salon apron, comfortable elegant shoes, polished nail-technician outfit, feminine and SFW",
  esthetician: "wear a clean fitted spa tunic, tailored spa trousers, elegant flat shoes, minimal refined accessories, premium esthetician uniform, polished and SFW",
  tailor: "wear a fitted elegant blouse, high-waisted tailored trousers, measuring-tape accessory, chic waist apron, polished shoes, stylish tailor outfit, realistic and SFW",
  jeweler: "wear a fitted refined blouse, high-waisted tailored trousers or midi skirt, elegant blazer, sophisticated low heels, luxury jeweler outfit, polished and SFW",
  "interior-designer": "wear a fitted designer blouse, high-waisted wide-leg trousers, architectural blazer, stylish heels, sophisticated interior-designer outfit, creative and SFW",
  "construction-worker": "wear a fitted long-sleeve work shirt, durable high-waisted work trousers, high-visibility vest, hard hat, sturdy safety boots, realistic construction-worker outfit, practical and SFW",
  carpenter: "wear a fitted work shirt, durable utility trousers, practical tool belt, sturdy work boots, clean realistic carpenter outfit, functional and SFW",
  electrician: "wear a fitted work polo or long-sleeve shirt, durable utility trousers, practical tool belt, protective boots, realistic electrician outfit, professional and SFW",
  plumber: "wear a fitted work polo, durable utility trousers, practical tool belt, sturdy work boots, clean realistic plumber outfit, professional and SFW",
  welder: "wear a fitted flame-resistant work shirt, durable work trousers, protective leather apron, heavy work boots, welding gloves, realistic welder outfit, safe and SFW",
  mechanic: "wear a fitted mechanic work shirt, tailored utility work pants, clean coverall layer tied or worn neatly, sturdy work boots, authentic mechanic outfit, polished and SFW",
  "truck-driver": "wear a fitted casual work shirt, high-waisted durable jeans, practical lightweight jacket, sturdy boots, clean realistic truck-driver outfit, comfortable and SFW",
  "delivery-driver": "wear a fitted delivery polo, practical tailored cargo trousers, lightweight branded-style jacket without logos, clean sneakers, realistic delivery-driver outfit, SFW",
  "taxi-driver": "wear a fitted smart-casual blouse, tailored dark trousers, light cardigan or blazer, comfortable polished shoes, neat taxi-driver outfit, realistic and SFW",
  pilot: "wear a fitted white pilot shirt with epaulets, tailored dark trousers, structured aviation blazer, polished black shoes, authentic elegant pilot uniform, realistic and SFW",
  "flight-attendant": "wear a elegant fitted airline-style blouse, tailored knee-length skirt, structured cropped jacket, neck scarf, refined heels, polished flight-attendant uniform, realistic and SFW",
  "travel-agent": "wear a fitted elegant blouse, high-waisted tailored trousers or skirt, light blazer, refined heels, polished travel-agent outfit, welcoming and SFW",
  "tour-guide": "wear a fitted breathable blouse, high-waisted tailored shorts or trousers with tasteful coverage, lightweight jacket, comfortable stylish sneakers, polished tour-guide outfit, SFW",
  "hotel-manager": "wear a elegant fitted blouse, high-waisted pencil skirt or tailored trousers, luxury blazer, refined heels, premium hotel-manager outfit, polished and SFW",
  housekeeper: "wear a clean fitted housekeeping tunic or blouse, tailored work trousers, neat waist apron, comfortable closed-toe shoes, polished hotel-housekeeper uniform, realistic and SFW",
  caregiver: "wear a soft fitted polo or blouse, comfortable tailored trousers, light cardigan, clean supportive shoes, warm professional caregiver outfit, practical and SFW",
  "social-worker": "wear a soft fitted blouse, tailored trousers, lightweight blazer, comfortable refined shoes, approachable social-worker outfit, polished and SFW",
  "childcare-worker": "wear a fitted comfortable cotton top, high-waisted practical trousers, light cardigan, clean sneakers, cheerful childcare-worker outfit, practical and SFW",
  "stay-at-home-parent": "wear a cute fitted casual top, high-waisted jeans or soft tailored shorts with tasteful coverage, cozy cardigan, stylish flats, attractive modern stay-at-home outfit, comfortable and SFW",
  retired: "wear a elegant fitted casual blouse, high-waisted relaxed trousers or midi skirt, refined cardigan, comfortable stylish shoes, polished mature lifestyle outfit, SFW",
  freelancer: "wear a fitted contemporary top, high-waisted smart-casual trousers or jeans, light cropped blazer, stylish sneakers, polished freelancer outfit, relaxed and SFW",
  "remote-worker": "wear a fitted soft knit top, high-waisted smart-casual trousers, cozy tailored cardigan, clean minimalist sneakers, attractive remote-work outfit, comfortable and SFW",
  unemployed: "wear a stylish fitted casual top, high-waisted jeans or tailored trousers, light fashionable jacket, clean sneakers, polished everyday lifestyle outfit, tasteful and SFW",
};

const OCCUPATION_CONTEXT_GROUPS: Array<{
  ids: string[];
  place: string;
}> = [
  { ids: ["doctor", "nurse", "dentist", "pharmacist", "surgeon", "paramedic", "physical-therapist", "nutritionist", "caregiver"], place: "modern bright hospital or medical clinic interior" },
  { ids: ["veterinarian"], place: "modern veterinary clinic interior" },
  { ids: ["teacher", "professor", "school-principal", "librarian", "student"], place: "modern elegant school or university interior" },
  { ids: ["software-developer", "data-analyst", "data-scientist", "product-manager", "project-manager", "ai-engineer", "cybersecurity-specialist", "network-engineer", "it-support", "database-administrator", "ux-designer", "ui-designer", "web-designer", "remote-worker"], place: "modern technology office with elegant workstations" },
  { ids: ["engineer", "architect", "civil-engineer", "mechanical-engineer", "electrical-engineer", "industrial-engineer", "aerospace-engineer"], place: "modern professional design and engineering studio" },
  { ids: ["lawyer", "judge", "paralegal"], place: "elegant modern law office interior" },
  { ids: ["business-owner", "accountant", "administrator", "marketing-specialist", "human-resources", "recruiter", "banker", "financial-advisor", "economist", "investment-analyst", "entrepreneur", "consultant", "operations-manager", "customer-service", "receptionist", "executive-assistant", "secretary", "office-worker"], place: "elegant modern corporate office interior" },
  { ids: ["salesperson", "store-manager"], place: "modern upscale retail store interior" },
  { ids: ["psychologist", "therapist", "social-worker"], place: "warm modern private consultation office" },
  { ids: ["scientist", "researcher", "biologist", "chemist", "physicist"], place: "clean modern research laboratory" },
  { ids: ["chef", "baker", "pastry-chef", "butcher"], place: "modern professional kitchen interior" },
  { ids: ["barista", "bartender", "waiter"], place: "stylish upscale cafe or restaurant interior" },
  { ids: ["photographer", "graphic-designer", "illustrator", "animator", "video-editor", "filmmaker", "director", "producer", "writer", "journalist", "copywriter", "translator", "interpreter"], place: "stylish modern creative studio interior" },
  { ids: ["model", "actor", "musician", "singer", "dancer", "content-creator", "influencer", "social-media-manager", "public-relations"], place: "luxurious modern photo and content studio" },
  { ids: ["coach", "personal-trainer", "athlete", "yoga-instructor", "fitness-instructor"], place: "premium modern fitness studio or gym" },
  { ids: ["police-officer", "security-guard", "detective"], place: "modern professional security or operations facility" },
  { ids: ["firefighter"], place: "modern fire station interior" },
  { ids: ["military-officer"], place: "modern military administrative facility" },
  { ids: ["real-estate-agent", "insurance-agent", "travel-agent", "hotel-manager"], place: "luxurious modern client-facing office or hotel lobby" },
  { ids: ["fashion-designer", "stylist", "hair-stylist", "makeup-artist", "nail-technician", "esthetician", "tailor", "jeweler", "interior-designer", "florist"], place: "elegant modern fashion, beauty or design studio" },
  { ids: ["construction-worker", "carpenter", "electrician", "plumber", "welder", "mechanic"], place: "clean modern workshop or active professional worksite" },
  { ids: ["farmer", "gardener"], place: "beautiful well-kept outdoor garden or farm setting" },
  { ids: ["truck-driver", "delivery-driver", "taxi-driver"], place: "clean modern transport or logistics setting" },
  { ids: ["pilot", "flight-attendant"], place: "modern premium airport or aircraft cabin setting" },
  { ids: ["tour-guide"], place: "beautiful modern urban landmark setting" },
  { ids: ["housekeeper"], place: "luxurious modern hotel interior" },
  { ids: ["childcare-worker", "stay-at-home-parent"], place: "bright comfortable modern home interior" },
  { ids: ["freelancer", "unemployed", "retired"], place: "elegant modern lifestyle interior" },
];

function getCustomOccupationContext(customValue?: string): OccupationGenerationContext {
  const occupation = customValue?.trim().replace(/\s+/g, " ").slice(0, 80);
  if (!occupation) {
    return {
      place: "elegant modern professional or lifestyle environment",
      clothes: "wear a stylish, flattering and realistic outfit appropriate for the person's occupation, with clear role-appropriate garments and accessories, tasteful and SFW",
    };
  }

  // The free-text occupation can be in any language. Keep the surrounding prompt
  // in English and preserve the user's value verbatim so the image model still
  // receives the exact role they entered.
  return {
    place: `a realistic, attractive environment naturally appropriate for someone whose occupation is: ${occupation}`,
    clothes: `wear a stylish, flattering and realistic outfit authentically appropriate for the occupation: ${occupation}; use recognizable role-appropriate garments, footwear and subtle accessories, feminine and polished when appropriate, tasteful and SFW`,
  };
}

export function getOccupationGenerationContext(
  id: string | undefined,
  customValue?: string,
): OccupationGenerationContext {
  if (id === "custom") return getCustomOccupationContext(customValue);

  const group = OCCUPATION_CONTEXT_GROUPS.find((item) => item.ids.includes(id || ""));
  const clothes = id ? OCCUPATION_CLOTHES[id] : undefined;

  return {
    place: group?.place || "elegant modern professional or lifestyle interior appropriate to the occupation",
    clothes:
      clothes ||
      "wear a stylish, flattering and realistic outfit clearly appropriate to the occupation, with recognizable role-specific garments and accessories, tasteful and SFW",
  };
}
