"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { Check } from "lucide-react";
import { toast } from "sonner";
import { getAiModel, listBodyVariants, listBubbleButtVariants, saveAiModelDraft, setAiModelBody } from "@/lib/ai-model-api";
import { listModelGenerationAssets } from "@/lib/model-generation-assets-api";
import type { BodyVariant } from "@/types/ai-model";
import type { ModelGenerationAsset, ModelGenerationToolKey } from "@/types/model-generation-asset";

type BodyControlState={hips:number;buttSize:number;breasts:number;height:number;bubbleButt:number;waist:number;complexion:"slim"|"thick"};
const DEFAULT_BODY:BodyControlState={hips:1,buttSize:0,breasts:0,height:0,bubbleButt:0,waist:0,complexion:"slim"};
const BODY_TOOLS:ModelGenerationToolKey[]=["hips","butt_size","breasts","height","bubble_butt","waist","complexion"];
const HIP_LABELS=["Small Hips","Medium Hips","Big Hips","Huge Hips"];
function ordered(items:ModelGenerationAsset[]){return [...items].sort((a,b)=>(a.position??9999)-(b.position??9999)||a.sort_order-b.sort_order||a.id-b.id)}
function nearestAsset(items:ModelGenerationAsset[],ratio:number){const rows=ordered(items);if(!rows.length)return null;return rows[Math.round(Math.max(0,Math.min(1,ratio))*(rows.length-1))]??rows[0]}

export function BodyProportionsStep({modelId,onComplete}:{modelId:number;onComplete:()=>void}){
 const [bodyVariants,setBodyVariants]=useState<BodyVariant[]>([]); const [assets,setAssets]=useState<Record<string,ModelGenerationAsset[]>>({});
 const [body,setBody]=useState(DEFAULT_BODY); const [curvy,setCurvy]=useState(false); const [saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([getAiModel(modelId),listBodyVariants("woman"),...BODY_TOOLS.map(t=>listModelGenerationAssets(t).catch(()=>({items:[],total:0})))])
 .then(([m,c,...catalogs])=>{setBodyVariants(c.items);const map:Record<string,ModelGenerationAsset[]>={};BODY_TOOLS.forEach((t,i)=>map[t]=ordered(catalogs[i].items));setAssets(map);const d=m.draft_json as any;if(d?.bodyProportions)setBody({...DEFAULT_BODY,...d.bodyProportions});setCurvy(d?.bodyMode==="curvy")}).catch(e=>toast.error(e instanceof Error?e.message:"No se pudieron cargar las proporciones"))},[modelId]);
 const preview=useMemo(()=>({hips:nearestAsset(assets.hips??[],body.hips/3),butt_size:nearestAsset(assets.butt_size??[],body.buttSize/(curvy?7:6)),breasts:nearestAsset(assets.breasts??[],(body.breasts+5)/10),height:nearestAsset(assets.height??[],(body.height+5)/10),bubble_butt:nearestAsset(assets.bubble_butt??[],body.bubbleButt/.7),waist:nearestAsset(assets.waist??[],(body.waist+3)/6),complexion:(assets.complexion??[]).find(x=>(x.title||x.asset_key).toLowerCase().includes(body.complexion))??nearestAsset(assets.complexion??[],body.complexion==="slim"?0:1)}),[assets,body,curvy]);
 const set=<K extends keyof BodyControlState>(k:K,v:BodyControlState[K])=>setBody(s=>({...s,[k]:v}));
 async function confirm(){if(!bodyVariants.length){toast.error("No hay presets corporales base disponibles.");return}setSaving(true);try{const hipsVals=[...new Set(bodyVariants.map(x=>x.hips_size))].sort((a,b)=>a-b);const breastVals=[...new Set(bodyVariants.map(x=>x.breasts_size))].sort((a,b)=>a-b);const targetHip=hipsVals[Math.round((body.hips/3)*Math.max(hipsVals.length-1,0))]??hipsVals[0];const targetBreast=breastVals[Math.round(((body.breasts+5)/10)*Math.max(breastVals.length-1,0))]??breastVals[0];const preset=[...bodyVariants].sort((a,b)=>Math.abs(a.hips_size-targetHip)+Math.abs(a.breasts_size-targetBreast))[0];if(!preset)throw new Error("No se pudo resolver el preset corporal base.");const bubbles=await listBubbleButtVariants(preset.id);const bubble=bubbles.items[Math.round((body.bubbleButt/.7)*Math.max(bubbles.items.length-1,0))]??bubbles.items[0];if(!bubble)throw new Error("Este cuerpo no tiene Butt Elevation disponible.");const m=await getAiModel(modelId);const current=(m.draft_json&&typeof m.draft_json==="object")?m.draft_json:{};await saveAiModelDraft(modelId,{...current,bodyProportions:body,bodyMode:curvy?"curvy":"fit"},m.name);await setAiModelBody(modelId,preset.id,bubble.id);onComplete()}catch(e){toast.error(e instanceof Error?e.message:"No se pudieron guardar las proporciones")}finally{setSaving(false)}}
 return <div className="modelEmbeddedBodyStep"><div className="modelV2Complexion"><label>Complexion</label><div>{(["slim","thick"] as const).map(v=><button key={v} className={body.complexion===v?"active":""} onClick={()=>set("complexion",v)}>{preview.complexion&&body.complexion===v?<AssetPreview asset={preview.complexion}/>:null}<b>{v==="slim"?"Slim":"Thick"}</b></button>)}</div></div><div className="modelV2ControlsGrid">
 <Control label="Hips" value={body.hips} display={HIP_LABELS[body.hips]} min={0} max={3} step={1} left="Small" right="Huge" asset={preview.hips} onChange={v=>set("hips",v)}/>
 <div><div className="modelV2ModeRow"><strong>Butt Size</strong><span><button className={!curvy?"active":""} onClick={()=>{setCurvy(false);if(body.buttSize>6)set("buttSize",6)}}>Fit</button><button className={curvy?"active":""} onClick={()=>setCurvy(true)}>Curvy</button></span></div><Control label="" value={body.buttSize} display={`+${body.buttSize}`} min={0} max={curvy?7:6} step={1} left="0" right={`+${curvy?7:6}`} asset={preview.butt_size} onChange={v=>set("buttSize",v)}/></div>
 <Control label="Breasts" value={body.breasts} display={body.breasts>0?`+${body.breasts}`:`${body.breasts}`} min={-5} max={5} step={1} left="-5" right="+5" asset={preview.breasts} onChange={v=>set("breasts",v)}/><Control label="Height" value={body.height} display={body.height>0?`+${body.height}`:`${body.height}`} min={-5} max={5} step={1} left="-5" right="+5" asset={preview.height} onChange={v=>set("height",v)}/><Control label="Bubble Butt" value={body.bubbleButt} display={body.bubbleButt.toFixed(1)} min={0} max={.7} step={.1} left="0" right="0.7" asset={preview.bubble_butt} onChange={v=>set("bubbleButt",Number(v.toFixed(1)))}/><Control label="Waist" value={body.waist} display={body.waist>0?`+${body.waist}`:`${body.waist}`} min={-3} max={3} step={1} left="-3" right="+3" asset={preview.waist} onChange={v=>set("waist",v)}/></div><div className="faceStepConfirmRow"><button type="button" className="faceChooseButton" onClick={confirm} disabled={saving}><Check size={17}/>{saving?"Guardando…":"Elegir"}</button></div></div>
}
function AssetPreview({asset}:{asset:ModelGenerationAsset}){const src=asset.poster_url||asset.video_url;return src?<span className="modelV2AssetPreview">{asset.video_url&&!asset.poster_url?<video src={asset.video_url} muted playsInline/>:<img src={src} alt=""/>}</span>:null}
function Control({label,value,display,min,max,step,left,right,asset,onChange}:{label:string;value:number;display:string;min:number;max:number;step:number;left:string;right:string;asset:ModelGenerationAsset|null;onChange:(v:number)=>void}){return <div className="modelV2Control">{asset&&<AssetPreview asset={asset}/>}<div className="modelV2ControlMain"><div className="modelV2ControlHead"><strong>{label}</strong><output>{display}</output></div><Slider value={value} min={min} max={max} step={step} onChange={onChange}/><div className="modelAxisEnds"><span>{left}</span><span>{right}</span></div></div></div>}
function Slider({value,min,max,step,onChange}:{value:number;min:number;max:number;step:number;onChange:(v:number)=>void}){const ref=useRef<HTMLDivElement|null>(null),drag=useRef(false);const percent=((value-min)/Math.max(max-min,step))*100;const update=(x:number)=>{const el=ref.current;if(!el)return;const r=el.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(x-r.left)/Math.max(r.width,1))),raw=min+ratio*(max-min),next=Math.max(min,Math.min(max,Math.round((raw-min)/step)*step+min));onChange(Number(next.toFixed(4)))};return <div ref={ref} className="modelDiscreteSlider" role="slider" tabIndex={0} aria-valuemin={min} aria-valuemax={max} aria-valuenow={value} onPointerDown={(e:ReactPointerEvent<HTMLDivElement>)=>{drag.current=true;e.currentTarget.setPointerCapture(e.pointerId);update(e.clientX)}} onPointerMove={(e:ReactPointerEvent<HTMLDivElement>)=>{if(drag.current)update(e.clientX)}} onPointerUp={e=>{drag.current=false;e.currentTarget.releasePointerCapture(e.pointerId)}}><div className="modelDiscreteRail"/><div className="modelDiscreteFill" style={{width:`${percent}%`}}/><span className="modelDiscreteThumb" style={{left:`${percent}%`}}/></div>}
