"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Check, Grid3X3, SlidersHorizontal, Sparkles, UserRound, X } from "lucide-react";
import { toast } from "sonner";
import { getAiModel,listBodyVariants,setAiModelBody } from "@/lib/ai-model-api";
import type { AiModelProfile,BodyVariant } from "@/types/ai-model";
import { ModelImage } from "./model-image";

const nearest=(rows:BodyVariant[],key:keyof Pick<BodyVariant,"hips_size"|"fat_thin"|"breasts_size">,value:number)=>rows.reduce((a,b)=>Math.abs(b[key]-value)<Math.abs(a[key]-value)?b:a,rows[0]);
export function ModelStudio({modelId}:{modelId:number}){
 const router=useRouter(); const [model,setModel]=useState<AiModelProfile|null>(null); const [items,setItems]=useState<BodyVariant[]>([]); const [selected,setSelected]=useState<BodyVariant|null>(null); const [gallery,setGallery]=useState(false); const [fatFilter,setFatFilter]=useState("all"); const [hipFilter,setHipFilter]=useState("all"); const [breastFilter,setBreastFilter]=useState("all"); const [saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([getAiModel(modelId),listBodyVariants("woman")]).then(([m,c])=>{setModel(m);setItems(c.items);setSelected(c.items.find(x=>x.id===m.body_proportion_preset_id)||c.items[0]||null)}).catch(e=>toast.error(e instanceof Error?e.message:"No se pudo cargar el estudio"))},[modelId]);
 const values=useMemo(()=>({hips:[...new Set(items.map(x=>x.hips_size))].sort((a,b)=>a-b),fat:[...new Set(items.map(x=>x.fat_thin))].sort((a,b)=>b-a),breasts:[...new Set(items.map(x=>x.breasts_size))].sort((a,b)=>a-b)}),[items]);
 const chooseAxis=(key:"hips_size"|"fat_thin"|"breasts_size",value:number)=>{if(!selected||!items.length)return; const scored=[...items].sort((a,b)=>{const score=(x:BodyVariant)=>Math.abs(x[key]-value)*100+Math.abs(x.hips_size-(key==="hips_size"?value:selected.hips_size))+Math.abs(x.fat_thin-(key==="fat_thin"?value:selected.fat_thin))+Math.abs(x.breasts_size-(key==="breasts_size"?value:selected.breasts_size));return score(a)-score(b)});setSelected(scored[0])};
 const filtered=items.filter(x=>(fatFilter==="all"||x.fat_band===fatFilter)&&(hipFilter==="all"||x.hips_band===hipFilter)&&(breastFilter==="all"||x.breast_band===breastFilter));
 const bands=(key:"fat_band"|"hips_band"|"breast_band")=>[...new Set(items.map(x=>x[key]).filter(Boolean))] as string[];
 async function confirm(){if(!selected)return;setSaving(true);try{const m=await setAiModelBody(modelId,selected.id);setModel(m);toast.success("Cuerpo guardado en tu modelo");}catch(e){toast.error(e instanceof Error?e.message:"No se pudo guardar")}finally{setSaving(false)}}
 if(!model)return <div className="modelLoading pageEnter"><span className="spinner"/><p>Preparando el estudio…</p></div>;
 return <div className="modelStudio pageEnter">
  <header className="modelStudioHead"><button onClick={()=>router.push("/models")} className="modelIconBtn"><ArrowLeft size={18}/></button><div><span className="eyebrow">CREATE MODEL IA · CUERPO</span><h1>{model.name}</h1><p>Define la silueta. Cada ajuste busca la variante generada más cercana, nunca inventa una imagen.</p></div><button className="modelGalleryBtn" onClick={()=>setGallery(true)}><Grid3X3 size={17}/> Ver todas las variantes</button></header>
  {items.length===0?<div className="modelEmpty"><Sparkles/><h2>Aún no hay cuerpos publicados</h2><p>Genera y guarda variantes desde Body Proportions en el BackOffice. Solo las imágenes listas aparecen aquí.</p></div>:<div className="modelBuilder">
   <section className="modelPreviewPanel">{selected&&<><ModelImage src={selected.image_url} alt={selected.display_name} className="modelHeroImage"/><div className="modelPreviewMeta"><span>VARIANTE ACTUAL</span><strong>{selected.display_name}</strong><small>Hips {selected.hips_size} · Fat/Thin {selected.fat_thin} · Breasts {selected.breasts_size}</small></div></>}</section>
   <section className="modelControls"><div className="modelStep"><span>01</span><div><small>PROPORCIONES</small><h2>Esculpe su cuerpo</h2></div></div>
    <Axis label="Hips" value={selected?.hips_size??0} values={values.hips} onChange={v=>chooseAxis("hips_size",v)}/><Axis label="Fat / Thin" value={selected?.fat_thin??0} values={values.fat} onChange={v=>chooseAxis("fat_thin",v)}/><Axis label="Breasts" value={selected?.breasts_size??0} values={values.breasts} onChange={v=>chooseAxis("breasts_size",v)}/>
    <div className="modelFineValues"><span>Skin tone <b>{selected?.skin_tone}</b></span><span>Hair length <b>{selected?.hair_length}</b></span></div>
    <button className="modelConfirm" onClick={confirm} disabled={!selected||saving}><Check size={17}/>{saving?"Guardando…":"Usar este cuerpo"}</button><p className="modelNextHint">El siguiente paso — rostro y unión con el cuerpo — queda preparado para la siguiente fase.</p>
   </section></div>}
  {gallery&&<div className="modelModal"><button className="modelModalBackdrop" onClick={()=>setGallery(false)} aria-label="Cerrar"/><div className="modelGallery"><header><div><span className="eyebrow">BIBLIOTECA CORPORAL</span><h2>Todas las variantes</h2><p>{filtered.length} de {items.length} disponibles</p></div><button className="modelIconBtn" onClick={()=>setGallery(false)}><X/></button></header><div className="modelFilters"><Filter label="Grasa" value={fatFilter} options={bands("fat_band")} onChange={setFatFilter}/><Filter label="Hips" value={hipFilter} options={bands("hips_band")} onChange={setHipFilter}/><Filter label="Breasts" value={breastFilter} options={bands("breast_band")} onChange={setBreastFilter}/></div><div className="modelGalleryGrid">{filtered.map(v=><button key={v.id} className={`modelVariant${selected?.id===v.id?" active":""}`} onClick={()=>{setSelected(v);setGallery(false)}}><ModelImage src={v.image_url} alt={v.display_name}/><div><strong>{v.display_name}</strong><small>H {v.hips_size} · F {v.fat_thin} · B {v.breasts_size}</small></div></button>)}</div></div></div>}
 </div>
}
function Axis({label,value,values,onChange}:{label:string;value:number;values:number[];onChange:(v:number)=>void}){const idx=Math.max(0,values.findIndex(v=>v===value));return <div className="modelAxis"><div><label>{label}</label><output>{value}</output></div><input type="range" min={0} max={Math.max(0,values.length-1)} step={1} value={idx<0?0:idx} onChange={e=>onChange(values[Number(e.target.value)]??value)}/><div className="modelAxisEnds"><span>{values[0]??"—"}</span><span>{values.at(-1)??"—"}</span></div></div>}
function Filter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="all">Todos</option>{options.map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
