"use client";
import type { GenerationInput } from "@/types/generation";

type Values=Record<string,unknown>;
export function initialGenerationValues(inputs:GenerationInput[]):Values{return Object.fromEntries(inputs.map(i=>[i.key,i.default_value??(i.input_type==="boolean"?false:"")]))}

// Backward/forward compatible alias used by the generation modules page.
export const buildInitialGenerationValues = initialGenerationValues;
export function validateGenerationValues(inputs:GenerationInput[],values:Values):string|null{for(const i of inputs){const v=values[i.key],r=i.validation??{};if(i.is_required&&(v===undefined||v===null||v===""))return `Completa: ${i.name}.`;if(typeof v==="string"){if(typeof r.min_length==="number"&&v.length<r.min_length)return `${i.name} requiere al menos ${r.min_length} caracteres.`;if(typeof r.max_length==="number"&&v.length>r.max_length)return `${i.name} permite máximo ${r.max_length} caracteres.`}if(typeof v==="number"){if(typeof r.min==="number"&&v<r.min)return `${i.name} debe ser mayor o igual a ${r.min}.`;if(typeof r.max==="number"&&v>r.max)return `${i.name} debe ser menor o igual a ${r.max}.`}}return null}
function options(i:GenerationInput){const o=i.validation?.options;return Array.isArray(o)?o.map(x=>typeof x==="string"?{label:x,value:x}:{label:String((x as any).label??(x as any).value),value:String((x as any).value??"")}):[]}
export function DynamicGenerationForm({inputs,values,onChange,disabled}:{inputs:GenerationInput[];values:Values;onChange:(v:Values)=>void;disabled?:boolean}){const set=(k:string,v:unknown)=>onChange({...values,[k]:v});return <div><p className="generationFileTransportNote">Tus archivos se preparan automáticamente para el motor de generación.</p><div className="generationInputs">{[...inputs].sort((a,b)=>a.position-b.position).map(i=>{const r=i.validation??{};if(i.input_type==="boolean")return <label key={i.key} className="generationCheck"><input type="checkbox" disabled={disabled} checked={Boolean(values[i.key])} onChange={e=>set(i.key,e.target.checked)}/><span>{i.name}</span></label>;if(i.input_type==="image"||i.input_type==="file")return <label key={i.key} className="generationUpload"><strong>{i.name}{i.is_required?" *":""}</strong><span>{i.description||"Selecciona un archivo"}</span><input type="file" disabled={disabled} accept={i.input_type==="image"?String(r.accept??"image/*"):String(r.accept??"")} onChange={e=>set(i.key,e.target.files?.[0]??null)}/>{values[i.key] instanceof File&&<><small>{(values[i.key] as File).name}</small>{i.input_type==="image"&&<img src={URL.createObjectURL(values[i.key] as File)} alt={`Vista previa de ${i.name}`} className="generationUploadPreview"/>}</>}</label>;if(i.input_type==="select")return <label key={i.key} className="generationField"><span>{i.name}{i.is_required?" *":""}</span><select disabled={disabled} value={String(values[i.key]??"")} onChange={e=>set(i.key,e.target.value)}><option value="">Selecciona una opción</option>{options(i).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;if(i.input_type==="textarea"||i.input_type==="json")return <label key={i.key} className="generationField"><span>{i.name}{i.is_required?" *":""}</span><textarea disabled={disabled} rows={Number(r.rows??(i.input_type==="json"?7:5))} value={i.input_type==="json"&&typeof values[i.key]!=="string"?JSON.stringify(values[i.key]??{},null,2):String(values[i.key]??"")} onChange={e=>set(i.key,e.target.value)}/></label>;return <label key={i.key} className="generationField"><span>{i.name}{i.is_required?" *":""}</span><input disabled={disabled} type={i.input_type==="integer"||i.input_type==="float"?"number":"text"} step={i.input_type==="integer"?1:i.input_type==="float"?"any":undefined} min={typeof r.min==="number"?r.min:undefined} max={typeof r.max==="number"?r.max:undefined} minLength={typeof r.min_length==="number"?r.min_length:undefined} maxLength={typeof r.max_length==="number"?r.max_length:undefined} placeholder={typeof r.placeholder==="string"?r.placeholder:undefined} value={String(values[i.key]??"")} onChange={e=>set(i.key,i.input_type==="integer"?Number.parseInt(e.target.value||"0",10):i.input_type==="float"?Number(e.target.value):e.target.value)}/></label>})}</div></div>}
