"use client";
import "./generation-studio.css";
import { useEffect, useMemo, useState } from "react";
import { cancelGenerationExecution, executeGenerationModule, getGenerationExecution, listGenerationModules } from "@/lib/generation-api";
import type { GenerationExecution, GenerationInput, GenerationModule } from "@/types/generation";
import { normalizeGenerationError } from "@/lib/generation-errors";

async function fileToDataUrl(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("No se pudo leer el archivo.")); reader.readAsDataURL(file); }); }
function InputControl({input,value,onChange}:{input:GenerationInput;value:unknown;onChange:(v:unknown)=>void}) {
  if(input.input_type==="boolean") return <label className="generationCheck"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/><span>{input.name}</span></label>;
  if(input.input_type==="image"||input.input_type==="file") return <label className="generationUpload"><strong>{input.name}{input.is_required?" *":""}</strong><span>{input.description||"Selecciona un archivo"}</span><input type="file" accept={input.input_type==="image"?"image/*":undefined} onChange={async e=>{const f=e.target.files?.[0];onChange(f?await fileToDataUrl(f):null)}}/>{typeof value==="string"&&value.startsWith("data:image")&&<img src={value} alt="Vista previa"/>}</label>;
  if(input.input_type==="json") return <label className="generationField"><span>{input.name}{input.is_required?" *":""}</span><textarea value={typeof value==="string"?value:JSON.stringify(value??{},null,2)} onChange={e=>onChange(e.target.value)} /></label>;
  return <label className="generationField"><span>{input.name}{input.is_required?" *":""}</span><input type={input.input_type==="integer"||input.input_type==="float"?"number":"text"} value={String(value??"")} onChange={e=>onChange(input.input_type==="integer"?Number.parseInt(e.target.value||"0",10):input.input_type==="float"?Number(e.target.value):e.target.value)} /></label>;
}
export function GenerationStudio(){
 const [modules,setModules]=useState<GenerationModule[]>([]),[selectedId,setSelectedId]=useState<number|null>(null),[values,setValues]=useState<Record<string,unknown>>({}),[execution,setExecution]=useState<GenerationExecution|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[pollFailures,setPollFailures]=useState(0);
 useEffect(()=>{listGenerationModules().then(r=>{setModules(r.items);setSelectedId(r.items[0]?.id??null)}).catch(e=>setError(normalizeGenerationError(e))).finally(()=>setBusy(false))},[]);
 const selected=useMemo(()=>modules.find(m=>m.id===selectedId)??null,[modules,selectedId]);
 useEffect(()=>{if(selected)setValues(Object.fromEntries(selected.inputs.map(i=>[i.key,i.default_value??(i.input_type==="boolean"?false:"")])));setExecution(null)},[selected]);
 useEffect(()=>{if(!execution||!["queued","running"].includes(execution.status))return;const timer=window.setInterval(()=>getGenerationExecution(execution.id).then(item=>{setExecution(item);setPollFailures(0)}).catch(()=>setPollFailures(value=>value+1)),1000);return()=>window.clearInterval(timer)},[execution]);
 async function run(){if(!selected)return;for(const i of selected.inputs){if(i.is_required&&(values[i.key]===undefined||values[i.key]===null||values[i.key]==="")){setError(`Completa: ${i.name}.`);return}}setBusy(true);setError(null);try{const normalized={...values};for(const i of selected.inputs.filter(x=>x.input_type==="json")){if(typeof normalized[i.key]==="string")normalized[i.key]=JSON.parse(normalized[i.key] as string)}setExecution(await executeGenerationModule(selected.id,normalized))}catch(e){setError(normalizeGenerationError(e))}finally{setBusy(false)}}
 if(busy&&!modules.length)return <div className="generationEmpty">Cargando módulos de generación…</div>;
 return <div className="generationStudio"><section className="generationHero"><span>MÓDULOS DINÁMICOS</span><h1>Genera desde la configuración real del BackOffice.</h1><p>Los campos aparecen directamente desde el backend. El runtime aplica propiedad por usuario, límite de concurrencia y ejecución simulada segura.</p></section>{error&&<div className="generationError" role="alert">{error}</div>}{pollFailures>=3&&<div className="generationError" role="status">La conexión con el estado de la ejecución está inestable. Seguiremos intentando automáticamente.</div>}<div className="generationLayout"><aside className="generationModules"><small>MÓDULO</small>{modules.map(m=><button key={m.id} className={m.id===selectedId?"active":""} onClick={()=>setSelectedId(m.id)}><strong>{m.name}</strong><span>{m.category} · v{m.version}</span></button>)}{!modules.length&&<p>No hay módulos activos. Activa uno desde BackOffice.</p>}</aside><main className="generationPanel">{selected&&<><div className="generationTitle"><div><small>{selected.key}</small><h2>{selected.name}</h2><p>{selected.description||"Sin descripción."}</p></div><div><span className="generationBadge">Simulado seguro</span>{selected.pricing?<p style={{marginTop:8,fontSize:13,color:"#f4f4f5",textAlign:"right"}}>{selected.pricing.required_tokens} tokens · {selected.pricing.final_price_usd.toFixed(2)} {selected.pricing.currency}</p>:<p style={{marginTop:8,fontSize:12,color:"#f87171",textAlign:"right"}}>Sin precio configurado</p>}</div></div><div className="generationInputs">{[...selected.inputs].sort((a,b)=>a.position-b.position).map(i=><InputControl key={i.key} input={i} value={values[i.key]} onChange={v=>setValues(x=>({...x,[i.key]:v}))}/>)}</div><button className="primaryButton generationRun" disabled={busy||!selected.pricing?.is_active||!!execution&&["queued","running"].includes(execution.status)} onClick={run}>{execution&&["queued","running"].includes(execution.status)?`Procesando ${execution.progress}%`:selected.pricing?.is_active?`Ejecutar por ${selected.pricing.required_tokens} tokens ✦`:"Precio no configurado"}</button></>}</main><aside className="generationExecution"><small>EJECUCIÓN</small>{execution?<><div className="generationStatus"><strong>{execution.status}</strong><span>{execution.progress}%</span></div><div className="generationProgress"><i style={{width:`${execution.progress}%`}}/></div><div className="generationLogs">{execution.logs.slice(-8).map((l,i)=><p key={`${l.timestamp}-${i}`}><span>{new Date(l.timestamp).toLocaleTimeString()}</span>{l.message}</p>)}</div>{["queued","running"].includes(execution.status)&&<button onClick={()=>cancelGenerationExecution(execution.id).then(setExecution)}>Cancelar</button>}{execution.status==="completed"&&<pre>{JSON.stringify(execution.outputs,null,2)}</pre>}{execution.error&&<div className="generationError">{execution.error}</div>}</>:<p>Ejecuta un módulo para ver progreso, logs y resultados.</p>}</aside></div></div>
}
