"use client";
import "./generation-studio.css";
import { useEffect, useMemo, useState } from "react";
import { cancelGenerationExecution, executeGenerationModule, getGenerationExecution, listGenerationExecutions, listGenerationModules } from "@/lib/generation-api";
import type { GenerationExecution, GenerationModule } from "@/types/generation";
import { normalizeGenerationError } from "@/lib/generation-errors";
import { DynamicGenerationForm, initialGenerationValues, validateGenerationValues } from "@/components/generation/dynamic-generation-form";
import { GenerationResults } from "@/components/generation/generation-results";
import { useGenerationJobs } from "@/components/generation/generation-jobs-provider";
const ACTIVE=["queued","running"];
export function GenerationStudio(){
 const {track}=useGenerationJobs();
 const [modules,setModules]=useState<GenerationModule[]>([]),[selectedId,setSelectedId]=useState<number|null>(null),[values,setValues]=useState<Record<string,unknown>>({}),[execution,setExecution]=useState<GenerationExecution|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[pollFailures,setPollFailures]=useState(0),[restoring,setRestoring]=useState(false);
 useEffect(()=>{listGenerationModules().then(r=>{setModules(r.items);setSelectedId(r.items[0]?.id??null)}).catch(e=>setError(normalizeGenerationError(e))).finally(()=>setBusy(false))},[]);
 const selected=useMemo(()=>modules.find(m=>m.id===selectedId)??null,[modules,selectedId]);
 useEffect(()=>{if(!selected)return;setValues(initialGenerationValues(selected.inputs));setRestoring(true);listGenerationExecutions({moduleId:selected.id,limit:1}).then(r=>setExecution(r.items[0]??null)).catch(e=>setError(normalizeGenerationError(e))).finally(()=>setRestoring(false))},[selected]);
 useEffect(()=>{if(!execution||!ACTIVE.includes(execution.status))return;track(execution);const timer=window.setInterval(()=>getGenerationExecution(execution.id).then(item=>{setExecution(item);track(item);setPollFailures(0)}).catch(()=>setPollFailures(v=>v+1)),1000);return()=>window.clearInterval(timer)},[execution?.id,execution?.status,track]);
 async function run(){if(!selected)return;const validationError=validateGenerationValues(selected.inputs,values);if(validationError){setError(validationError);return}setBusy(true);setError(null);try{const normalized={...values};for(const i of selected.inputs.filter(x=>x.input_type==="json")){if(typeof normalized[i.key]==="string")normalized[i.key]=JSON.parse(normalized[i.key] as string)}const job=await executeGenerationModule(selected.id,normalized);setExecution(job);track(job)}catch(e){setError(normalizeGenerationError(e))}finally{setBusy(false)}}
 if(busy&&!modules.length)return <div className="generationEmpty">Cargando módulos de generación…</div>;
 return <div className="generationStudio"><section className="generationHero"><span>MÓDULOS DINÁMICOS</span><h1>Genera desde la configuración real del BackOffice.</h1><p>Las ejecuciones se conservan aunque recargues, cierres el navegador o vuelvas a iniciar sesión.</p></section>{error&&<div className="generationError" role="alert">{error}</div>}{pollFailures>=3&&<div className="generationError" role="status">La conexión está inestable. Seguiremos intentando automáticamente.</div>}<div className="generationLayout"><aside className="generationModules"><small>MÓDULO</small>{modules.map(m=><button key={m.id} className={m.id===selectedId?"active":""} onClick={()=>setSelectedId(m.id)}><strong>{m.name}</strong><span>{m.category} · v{m.version}</span></button>)}</aside><main className="generationPanel">{selected&&<><div className="generationTitle"><div><small>{selected.key}</small><h2>{selected.name}</h2><p>{selected.description||"Sin descripción."}</p></div><div><span className="generationBadge">{selected.default_execution_engine.replaceAll("_"," ")}</span></div></div><DynamicGenerationForm inputs={selected.inputs} values={values} onChange={setValues} disabled={busy||restoring}/><button className="primaryButton generationRun" disabled={busy||restoring||!selected.pricing?.is_active||!!execution&&ACTIVE.includes(execution.status)} onClick={run}>{restoring?"Recuperando ejecución…":execution&&ACTIVE.includes(execution.status)?`Procesando ${execution.progress}%`:selected.pricing?.is_active?`Ejecutar por ${selected.pricing.required_tokens} tokens ✦`:"Precio no configurado"}</button></>}</main><aside className="generationExecution"><small>EJECUCIÓN</small>{restoring?<p>Recuperando el estado más reciente…</p>:execution?<><div className="generationStatus"><strong>{execution.status}</strong><span>{execution.progress}%</span></div><div className="generationProgress"><i style={{width:`${execution.progress}%`}}/></div><div className="generationLogs">{execution.logs.slice(-8).map((l,i)=><p key={`${l.timestamp}-${i}`}><span>{new Date(l.timestamp).toLocaleTimeString()}</span>{l.message}</p>)}</div>{ACTIVE.includes(execution.status)&&<button onClick={()=>cancelGenerationExecution(execution.id).then(item=>{setExecution(item);track(item)})}>Cancelar</button>}{execution.status==="completed"&&<GenerationResults outputs={execution.outputs}/>} {execution.error&&<div className="generationError">{execution.error}</div>}</>:<p>No hay ejecuciones previas para este módulo.</p>}</aside></div></div>;
}
