"use client";
import {useEffect,useRef,useState} from "react";
import {deleteLibraryFile,listLibrary,uploadLibraryFile,type LibraryFile,type LibraryUsage} from "@/lib/user-library-api";
export function LibraryFilePicker({accept="image/*",disabled,onSelect}:{accept?:string;disabled?:boolean;onSelect:(file:File|LibraryFile)=>void}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<LibraryFile[]>([]),[usage,setUsage]=useState<LibraryUsage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null); const input=useRef<HTMLInputElement>(null);
 const load=async()=>{try{const r=await listLibrary();setItems(r.items);setUsage(r.usage)}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar la librería")}};
 useEffect(()=>{if(open)void load()},[open]);
 const upload=async(file:File)=>{setBusy(true);setError(null);try{const saved=await uploadLibraryFile(file);onSelect(file);setItems(x=>[saved,...x.filter(i=>i.id!==saved.id)]);await load();setOpen(false)}catch(e){setError(e instanceof Error?e.message:"No fue posible subir el archivo")}finally{setBusy(false)}};
 return <div className="libraryPicker"><div className="libraryPickerActions"><button type="button" disabled={disabled||busy} onClick={()=>setOpen(true)}>Mi librería</button><button type="button" disabled={disabled||busy} onClick={()=>input.current?.click()}>Subir nuevo</button><input ref={input} hidden type="file" accept={accept} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></div>
 {open&&<div className="libraryPickerModal" role="dialog" aria-modal="true"><div className="libraryPickerPanel"><header><div><strong>Mi librería</strong>{usage&&<small>{(usage.used_bytes/1048576).toFixed(1)} MB de {(usage.quota_bytes/1048576).toFixed(0)} MB</small>}</div><button type="button" onClick={()=>setOpen(false)}>Cerrar</button></header>{usage&&<div className="libraryUsage"><span style={{width:`${Math.min(100,usage.percent_used)}%`}}/></div>}{error&&<p className="libraryError">{error}</p>}<div className="libraryGrid">{items.map(item=><article key={item.id}><button type="button" className="libraryThumb" onClick={async()=>{const r=await fetch(item.url);const b=await r.blob();onSelect(new File([b],item.filename,{type:item.content_type||b.type}));setOpen(false)}}>{item.content_type?.startsWith("image/")?<img src={item.url} alt={item.filename}/>:<span>ARCHIVO</span>}<small>{item.filename}</small></button><button type="button" className="libraryDelete" onClick={async()=>{await deleteLibraryFile(item.id);await load()}}>Eliminar</button></article>)}</div>{items.length===0&&<p className="libraryEmpty">Tu librería está vacía.</p>}</div></div>}</div>
}
